kind: pipeline
name: 4.12.0+domains

platform:
  os: linux
  arch: amd64

steps:
- name: 4.12.0+domains
  image: ocaml/opam:debian-10-ocaml-4.12-domains
  commands:
  - opam repo add --set-default .
  - eval $(opam env)
  - opam install -y dune domainslib
